version: '3.7'
services:
  db:
    image: postgres:12.3
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust  # Insecure connection, only for local
    networks:
      - backend
  web:
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    ports:
      - "3000:3000"
    environment:
      RAILS_SERVE_STATIC_FILES: 'true'
      DATABASE_URL: postgresql://user:password@host:5432
      SECRET_KEY_BASE: supersecretandrandomkey
      NODE_ENV: production
      RAILS_ENV: production
    env_file: .env
    depends_on:
      - db
    networks:
      - backend

volumes:
  data:
    driver: local

networks:
  backend:
