production:
  adapter: redis
  url: redis://redis:6379
  channel_prefix: rails_vue_production

development:
  adapter: redis
  url: redis://redis:6379
  channel_prefix: rails_vue_development

test:
  adapter: test
